# -*- coding: utf-8 -*-
"""Batolito.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBMRDH62gxz4cq_kPlRHnh29VPDaS2c6

Modulo 1: Base
"""

// Archivo: App.js (React)
import React, { useState } from 'react';
import { Document, Page, pdfjs } from 'react-pdf';
import 'react-pdf/dist/esm/Page/AnnotationLayer.css';
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
function App() {
  const [pdfFile, setPdfFile] = useState(null);
  const [numPages, setNumPages] = useState(null);
  const [extractedText, setExtractedText] = useState('');
  function onFileChange(event) {
    const file = event.target.files[0];
    if (file) setPdfFile(file);
  }
  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
    extractTextFromPdf(pdfFile);
  }
  async function extractTextFromPdf(file) {
    if (!file) return;
    const pdf = await pdfjs.getDocument(URL.createObjectURL(file)).promise;
    let fullText = '';
    for (let i = 1; i <= pdf.numPages; i++) {
      const page = await pdf.getPage(i);
      const content = await page.getTextContent();
      const strings = content.items.map(item => item.str);
      fullText += strings.join(' ') + '\n\n';
    }
    setExtractedText(fullText);
  }
  return (
    <div style={{ padding: '20px' }}>
      <h1>Análisis Avanzado Batolito del Perú</h1>
      <input type="file" accept="application/pdf" onChange={onFileChange} />
      {pdfFile && (
        <Document
          file={pdfFile}
          onLoadSuccess={onDocumentLoadSuccess}
          loading="Cargando PDF..."
        >
          {[...Array(numPages)].map((_, index) => (
            <Page key={index} pageNumber={index + 1} width={600} />
          ))}
        </Document>
      )}
      <section style={{ marginTop: '40px' }}>
        <h2>Texto Extraído</h2>
        <textarea
          readOnly
          value={extractedText}
          style={{ width: '100%', height: '300px', whiteSpace: 'pre-wrap' }}
        />
      </section>
      {/* Aquí se integrarán visualizaciones científicas y mapas interactivos */}
    </div>
  );
}
export default App;

"""Modulo 2: Segmentar y extraer texto"""

import re
def segmentar_secciones(texto):
    """
    Segmenta el texto en secciones numeradas 3, 4 y 5
    Según títulos que comienzan con "3.", "4." o "5."
    Retorna diccionario con secciones como claves y texto como valor.
    """
    # Buscar los encabezados de seccion 3,4,5 usando regex
    patrones = {
        '3': r'(?:^|\n)(3\..*?)(?=\n[4]\.|[5]\.|$)',  # Sección 3 hasta antes de 4 o 5 o fin
        '4': r'(?:^|\n)(4\..*?)(?=\n[5]\.|$)',        # Sección 4 hasta antes de 5 o fin
        '5': r'(?:^|\n)(5\..*)'                        # Sección 5 hasta fin
    }
    secciones = {}
    for key, patron in patrones.items():
        match = re.search(patron, texto, re.DOTALL)
        if match:
            secciones[key] = match.group(1).strip()
        else:
            secciones[key] = "Sección no encontrada o vacía."
    return secciones
def extraer_palabras_clave(texto, palabras_clave):
    """
    Extrae frases o líneas donde aparecen palabras clave geológicas.
    """
    lineas = texto.split('\n')
    extraidas = []
    for linea in lineas:
        for palabra in palabras_clave:
            if palabra.lower() in linea.lower():
                extraidas.append(linea.strip())
                break
    return extraidas
if __name__ == "__main__":
    # Suponiendo que tienes texto extraído del PDF
    # Reemplazamos la lectura de archivo con un texto de ejemplo
    texto_completo = """
1. Introducción
Este es un texto de introducción.

2. Geología General
Aquí hablamos de geología general.

3. Petrografía de las Rocas Ígneas
Esta sección describe la petrografía ígnea avanzada. Se observa cristalización fraccionada en los magmas. La asimilación cortical es importante. Puede haber mezcla de magmas. Las granodioritas son abundantes. Se estudia el fabric mineral y los procesos de enfriamiento y emplazamiento.

4. Geoquímica
Análisis geoquímico de las rocas.

5. Conclusiones
Las conclusiones finales del estudio."""

    secciones = segmentar_secciones(texto_completo)
    # Definimos palabras clave para enfoque petrografía ígnea avanzada
    palabras_clave = [
        "cristalización fraccionada", "asimilación cortical", "mezcla de magmas",
        "petrográfica", "granodiorita", "fabric mineral", "enfriamiento", "emplazamiento"
    ]
    for num, contenido in secciones.items():
        print(f"\n--- Sección {num} ---\n")
        print(contenido[:800], '...\n')  # Mostrar un adelanto del texto
        claves = extraer_palabras_clave(contenido, palabras_clave)
        print("Frases con palabras clave relevantes:")
        for frase in claves:
            print("-", frase)

"""Modulo 3: API Backed / Fast Api (procesamiento avanzado)"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import re

app = FastAPI(title="API Análisis Batolito Perú")

class TextoRequest(BaseModel):
    texto: str

def segmentar_secciones(texto):
    patrones = {
        '3': r'(?:^|\n)(3\..*?)(?=\n[4]\.|[5]\.|$)',
        '4': r'(?:^|\n)(4\..*?)(?=\n[5]\.|$)',
        '5': r'(?:^|\n)(5\..*)'
    }
    secciones = {}
    for key, patron in patrones.items():
        match = re.search(patron, texto, re.DOTALL)
        if match:
            secciones[key] = match.group(1).strip()
        else:
            secciones[key] = ""
    return secciones

def extraer_palabras_clave(texto, palabras_clave):
    lineas = texto.split('\n')
    extraidas = []
    for linea in lineas:
        for palabra in palabras_clave:
            if palabra.lower() in linea.lower():
                extraidas.append(linea.strip())
                break
    return extraidas

@app.post("/procesar_texto")
def procesar_texto(request: TextoRequest):
    if not request.texto or len(request.texto) < 50:
        raise HTTPException(status_code=400, detail="Texto insuficiente para procesar")

    secciones = segmentar_secciones(request.texto)
    palabras_clave = [
        "cristalización fraccionada", "asimilación cortical", "mezcla de magmas",
        "petrográfica", "granodiorita", "fábrica mineral", "enfriamiento", "emplazamiento"
    ]

    resultado = {}
    for num, contenido in secciones.items():
        frases_clave = extraer_palabras_clave(contenido, palabras_clave)
        resultado[num] = {
            "contenido": contenido,
            "frases_clave": frases_clave
        }

    return {"secciones": resultado}

pip install fastapi uvicorn

uvicorn main:app --reload

const response = await fetch('http://127.0.0.1:8000/procesar_texto', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({ texto: textoExtraido })
});
const data = await response.json();
// data.secciones contendrá las secciones y frases clave

"""Modulo 4: Api Cientifica"""

// Archivo: App.js
import React, { useState } from 'react';
import { Document, Page, pdfjs } from 'react-pdf';

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

function App() {
  const [pdfFile, setPdfFile] = useState(null);
  const [numPages, setNumPages] = useState(null);
  const [extractedText, setExtractedText] = useState('');
  const [loading, setLoading] = useState(false);
  const [procesado, setProcesado] = useState(null);
  const [error, setError] = useState(null);

  const onFileChange = (event) => {
    const file = event.target.files[0];
    if (file) setPdfFile(file);
  };

  const onDocumentLoadSuccess = async ({ numPages }) => {
    setNumPages(numPages);
    const text = await extractTextFromPdf(pdfFile, numPages);
    setExtractedText(text);
    setProcesado(null);
    setError(null);
  };

  const extractTextFromPdf = (file, totalPages) => {
    return new Promise(async (resolve) => {
      const pdf = await pdfjs.getDocument(URL.createObjectURL(file)).promise;
      let fullText = '';
      for (let i = 1; i <= totalPages; i++) {
        const page = await pdf.getPage(i);
        const content = await page.getTextContent();
        const strings = content.items.map(item => item.str);
        fullText += strings.join(' ') + '\n\n';
      }
      resolve(fullText);
    });
  };

  const enviarTextoParaProcesar = async () => {
    setLoading(true);
    setProcesado(null);
    setError(null);
    try {
      const response = await fetch('http://127.0.0.1:8000/procesar_texto', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ texto: extractedText }),
      });
      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.detail || 'Error procesando texto');
      }
      const data = await response.json();
      setProcesado(data.secciones);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ maxWidth: 900, margin: 'auto', padding: 20 }}>
      <h1>Análisis Avanzado Batolito del Perú</h1>
      <input type="file" accept="application/pdf" onChange={onFileChange} />
      {pdfFile && (
        <Document
          file={pdfFile}
          onLoadSuccess={onDocumentLoadSuccess}
          loading="Cargando PDF..."
        >
          {[...Array(numPages)].map((_, idx) => (
            <Page key={idx} pageNumber={idx + 1} width={600} />
          ))}
        </Document>
      )}

      {extractedText && (
        <div style={{ marginTop: 20 }}>
          <button onClick={enviarTextoParaProcesar} disabled={loading}>
            {loading ? 'Procesando...' : 'Procesar Texto Científico'}
          </button>
        </div>
      )}

      {error && <p style={{ color: 'red' }}>Error: {error}</p>}

      {procesado && (
        <div style={{ marginTop: 20 }}>
          <h2>Resumen y Extracción por Sección</h2>
          {['3', '4', '5'].map((num) => (
            <section key={num} style={{ marginTop: 20 }}>
              <h3>Sección {num}</h3>
              <pre style={{ whiteSpace: 'pre-wrap', background: '#f4f4f4', padding: 10 }}>
                {procesado[num].contenido || 'No se encontró contenido para esta sección.'}
              </pre>
              <h4>Frases Clave Relevantes:</h4>
              {procesado[num].frases_clave.length ? (
                <ul>
                  {procesado[num].frases_clave.map((frase, i) => (
                    <li key={i}>{frase}</li>
                  ))}
                </ul>
              ) : (
                <p>No se encontraron frases clave.</p>
              )}
              {/* Aquí podrás luego agregar diagramas y mapas relacionados */}
            </section>
          ))}
        </div>
      )}
    </div>
  );
}

export default App;

"""Modulo 5: Módulo de diagramas interactivos científicos para la web"""

// Archivo: DiagramasCientificos.js
import React from 'react';
import Plot from 'react-plotly.js';

export default function DiagramasCientificos() {
  return (
    <div>
      <h3>Diagrama de Cristalización Fraccionada</h3>
      <Plot
        data={[
          {
            type: 'scatter',
            mode: 'lines+markers',
            x: [1, 2, 3, 4, 5],
            y: [1000, 800, 600, 400, 200],
            name: 'Temperatura (°C)',
            line: { shape: 'spline', color: 'royalblue' },
            marker: { size: 8 },
            yaxis: 'y1',
          },
          {
            type: 'bar',
            x: ['Magma inicial', 'Mineral precipitado', 'Magma residual', 'Cristales formados', 'Magma diferenciado'],
            y: [1, 0.8, 0.5, 0.3, 0.1],
            name: 'Concentración Relativa',
            marker: { color: 'firebrick' },
            yaxis: 'y2',
          },
        ]}
        layout={{
          width: 700,
          height: 400,
          title: 'Evolución de Temperatura y Concentración durante la Cristalización Fraccionada',
          yaxis: { title: 'Temperatura (°C)', side: 'left', range: [0, 1100] },
          yaxis2: { title: 'Concentración Relativa', overlaying: 'y', side: 'right' },
          legend: { x: 0.1, y: 1.1, orientation: 'h' },
          margin: { t: 40, b: 50 },
        }}
      />
    </div>
  );
}

npm install react-plotly.js plotly.js

import DiagramasCientificos from './DiagramasCientificos';

// Dentro de tu return, p.ej. al final:
{procesado && (
  <div style={{ marginTop: 40 }}>
    <DiagramasCientificos />
  </div>
)}

"""Diagrama 2: Esquema de Asimilación Cortical"""

// Archivo: AsimilacionCortical.js
import React from 'react';
import Plot from 'react-plotly.js';

export default function AsimilacionCortical() {
  return (
    <div>
      <h3>Diagrama de Asimilación Cortical</h3>
      <Plot
        data={[
          {
            type: 'scatter',
            mode: 'lines+markers',
            x: [0, 1, 2, 3, 4, 5],
            y: [100, 80, 60, 40, 20, 5],
            name: 'Concentración Magma Original',
            line: { color: 'blue' },
          },
          {
            type: 'scatter',
            mode: 'lines+markers',
            x: [0, 1, 2, 3, 4, 5],
            y: [0, 10, 20, 30, 40, 50],
            name: 'Asimilación Corteza',
            line: { color: 'red' },
          },
          {
            type: 'scatter',
            mode: 'lines+markers',
            x: [0, 1, 2, 3, 4, 5],
            y: [100, 90, 80, 70, 60, 55],
            name: 'Composición Magma Asimilado',
            line: { color: 'green' },
          }
        ]}
        layout={{
          width: 700,
          height: 400,
          title: 'Modelo de Asimilación Cortical en Magmas',
          xaxis: { title: 'Tiempo (Millones de Años)' },
          yaxis: { title: 'Concentración Relativa (%)' },
          margin: { t: 50 },
          legend: { orientation: 'h', y: -0.2 },
          plot_bgcolor: '#f9f9f9',
        }}
      />
    </div>
  );
}

"""Diagrama 3: Visualización esquemática de Mezcla de Magmas (Magma Mixing)"""

// Archivo: MezclaMagmas.js
import React from 'react';
import Plot from 'react-plotly.js';

export default function MezclaMagmas() {
  return (
    <div>
      <h3>Diagrama de Mezcla de Magmas</h3>
      <Plot
        data={[
          {
            x: [0, 1, 2, 3, 4, 5],
            y: [85, 70, 55, 50, 45, 40],
            type: 'scatter',
            mode: 'lines+markers',
            name: 'Magma Básico',
            line: { color: '#1f77b4' }
          },
          {
            x: [0, 1, 2, 3, 4, 5],
            y: [15, 30, 45, 50, 55, 60],
            type: 'scatter',
            mode: 'lines+markers',
            name: 'Magma Ácido',
            line: { color: '#ff7f0e' }
          },
          {
            x: [0, 1, 2, 3, 4, 5],
            y: [50, 50, 50, 50, 50, 50],
            type: 'scatter',
            mode: 'lines',
            name: 'Magma Mezclado',
            line: { dash: 'dash', color: '#2ca02c' }
          },
        ]}
        layout={{
          width: 700,
          height: 400,
          title: 'Proceso de Mezcla de Magmas en las Unidades Granodioríticas',
          xaxis: { title: 'Tiempo (miles de años)' },
          yaxis: { title: 'Proporción (%)' },
          margin: { t: 50 },
          legend: { orientation: 'h', y: -0.2 },
          plot_bgcolor: '#fffbe6',
        }}
      />
    </div>
  );
}

import DiagramasCientificos from './DiagramasCientificos';
import AsimilacionCortical from './AsimilacionCortical';
import MezclaMagmas from './MezclaMagmas';

// En el return, dentro de {procesado && (...)}

<DiagramasCientificos />
<AsimilacionCortical />
<MezclaMagmas />

"""Modulo 6: Mapa geológico interactivo con Leaflet y React-Leaflet"""

npm install leaflet react-leaflet

@import url("https://unpkg.com/leaflet@1.9.4/dist/leaflet.css");

// Archivo: MapaGeologico.js
import React from 'react';
import { MapContainer, TileLayer, GeoJSON, LayersControl } from 'react-leaflet';

const { BaseLayer, Overlay } = LayersControl;

// Ejemplo simplificado: GeoJSON de zonas geológicas (deberás usar datos reales)

const geojsonBatolito = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": { "nombre": "Granodiorita", "color": "#8B4513" },
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
          [-77.05, -12.1],
          [-77.03, -12.12],
          [-77.01, -12.11],
          [-77.02, -12.08],
          [-77.05, -12.1]
        ]]
      }
    },
    {
      "type": "Feature",
      "properties": { "nombre": "Diorita", "color": "#A0522D" },
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
          [-77.07, -12.13],
          [-77.04, -12.14],
          [-77.02, -12.13],
          [-77.03, -12.1],
          [-77.07, -12.13]
        ]]
      }
    }
  ]
};

function estilo(feature) {
  return {
    fillColor: feature.properties.color,
    weight: 2,
    opacity: 1,
    color: 'black',
    fillOpacity: 0.7,
  };
}

export default function MapaGeologico() {
  return (
    <div>
      <h3>Mapa Geológico Interactivo - Batolito del Perú</h3>
      <MapContainer center={[-12.1, -77.04]} zoom={12} style={{ height: "500px", width: "100%" }}>
        <LayersControl position="topright">
          <BaseLayer checked name="Mapa básico">
            <TileLayer
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              attribution="© OpenStreetMap"
            />
          </BaseLayer>
          <Overlay checked name="Unidades Geológicas">
            <GeoJSON data={geojsonBatolito} style={estilo} />
          </Overlay>
          {/* Puedes agregar más capas Overlay para otras propiedades, por ejemplo,
              historial geocronológico, fábricas minerales, etc */}
        </LayersControl>
      </MapContainer>
    </div>
  );
}

import MapaGeologico from './MapaGeologico';

// Y en tu return, probablemente luego de diagramas:
{procesado && (
  <>
    <DiagramasCientificos />
    <AsimilacionCortical />
    <MezclaMagmas />
    <MapaGeologico />
  </>
)}

"""Modulo 7: Generación dinámica de mapas mentales y diagramas conceptuales"""

npm install react-flow-renderer

// Archivo: MapaMental.js
import React, { useState, useCallback } from 'react';
import ReactFlow, {
  MiniMap,
  Controls,
  Background,
  addEdge,
  Handle,
} from 'react-flow-renderer';

const initialElements = [
  { id: '1', type: 'input', data: { label: 'Cristalización Fraccionada' }, position: { x: 250, y: 0 } },
  { id: '2', data: { label: 'Formación de minerales' }, position: { x: 100, y: 100 } },
  { id: '3', data: { label: 'Cambio en química del magma' }, position: { x: 400, y: 100 } },
  { id: '4', data: { label: 'Asimilación Cortical' }, position: { x: 250, y: 200 } },
  { id: '5', data: { label: 'Mezcla de Magmas' }, position: { x: 250, y: 300 } },
  { id: 'e1-2', source: '1', target: '2', animated: true },
  { id: 'e1-3', source: '1', target: '3' },
  { id: 'e3-4', source: '3', target: '4' },
  { id: 'e4-5', source: '4', target: '5', animated: true },
];

const MapaMental = () => {
  const [elements, setElements] = useState(initialElements);
  const onConnect = useCallback(
    (params) => setElements((els) => addEdge(params, els)),
    []
  );

  return (
    <div style={{ height: 500, border: '1px solid #ddd', marginTop: 20 }}>
      <h3>Mapa Mental Conceptual</h3>
      <ReactFlow elements={elements} onConnect={onConnect} snapToGrid={true} snapGrid={[15, 15]}>
        <MiniMap />
        <Controls />
        <Background color="#aaa" gap={16} />
      </ReactFlow>
    </div>
  );
};

export default MapaMental;

import MapaMental from './MapaMental';

// Dentro del return, bajo las visualizaciones previas
{procesado && <MapaMental />}

"""Backend para generación dinámica de mapa mental conceptual"""

from fastapi import FastAPI
from pydantic import BaseModel
import spacy
from spacy.matcher import PhraseMatcher

app = FastAPI(title="API Mapas Mentales Científicos Batolito Perú")

# Carga modelo spaCy en español
nlp = spacy.load("es_core_news_sm")

# Vocabulario geológico avanzado para detectar
terminos_petro = [
    "cristalización fraccionada",
    "asimilación cortical",
    "mezcla de magmas",
    "granodiorita",
    "batolito",
    "enfriamiento",
    "emplazamiento",
    "fábrica mineral",
    "plutón",
    "tectónica",
    "magma",
    "petrografía",
    "diferenciación magmática",
]

# Diccionario de definiciones para los términos geológicos
definiciones = {
    "cristalización fraccionada": "Proceso mediante el cual los minerales cristalizan a partir de un magma y se separan, cambiando la composición del magma residual.",
    "asimilación cortical": "Incorporación de material de la corteza terrestre al magma en formación, modificando su composición química.",
    "mezcla de magmas": "Proceso de interacción y mezcla física y química entre dos magmas de diferente composición.",
    "granodiorita": "Roca plutónica de composición intermedia a ácida, predominante en el batolito.",
    "batolito": "Gran cuerpo plutónico formado por la intrusión de magmas en la corteza terrestre.",
    "enfriamiento": "Proceso por el cual el magma pierde temperatura y solidifica.",
    "emplazamiento": "Colocación del magma en la corteza para formar cuerpos intrusivos.",
    "fábrica mineral": "Textura y orientación de los minerales en una roca que reflejan su historia de formación.",
    "plutón": "Cuerpo ígneo intrusivo de pequeño a mediano tamaño.",
    "tectónica": "Estudio de las deformaciones y estructuras en la corteza terrestre.",
    "magma": "Roca fundida en el interior de la Tierra.",
    "petrografía": "Estudio microscópico de rocas para determinar su composición y textura.",
    "diferenciación magmática": "Procesos que generan variabilidad composicional en magmas derivados de un mismo origen."
}

# Clasificación simple para posicionamiento
categorias = {
    "proceso": [
        "cristalización fraccionada",
        "asimilación cortical",
        "mezcla de magmas",
        "enfriamiento",
        "emplazamiento",
        "diferenciación magmática"
    ],
    "roca": [
        "granodiorita",
        "batolito",
        "plutón"
    ],
    "concepto": [
        "fábrica mineral",
        "tectónica",
        "magma",
        "petrografía"
    ]
}

# Preparar PhraseMatcher
matcher = PhraseMatcher(nlp.vocab, attr="LOWER")
patrones = [nlp(texto) for texto in terminos_petro]
matcher.add("TERMINOS_GEO", patrones)


class ConsultaRequest(BaseModel):
    texto: str


@app.post("/generar_mapa_mental")
def generar_mapa_mental(request: ConsultaRequest):
    doc = nlp(request.texto)

    nodos = {}
    relaciones = []

    # Nodo raíz tema completo
    nodos["0"] = {
        "id": "0",
        "data": {"label": request.texto[:60] + "... (Tema)"},
        "position": {"x": 300, "y": 0}
    }

    id_counter = 1

    # Detectar términos geológicos
    matches = matcher(doc)
    nodos_text_lower = set()

    for match_id, start, end in matches:
        span = doc[start:end]
        texto = span.text.lower()
        if texto in nodos_text_lower:
            continue
        nodos_text_lower.add(texto)

        # Categoría para posicionamiento
        categoria = "concepto"
        for cat, lista in categorias.items():
            if texto in lista:
                categoria = cat
                break

        # Posición X según categoría
        if categoria == "proceso":
            pos_x = 100
        elif categoria == "roca":
            pos_x = 400
        else:
            pos_x = 700

        pos_y = 100 + (id_counter * 60)

        nodos[str(id_counter)] = {
            "id": str(id_counter),
            "data": {
                "label": span.text,
                "description": definiciones.get(texto, "Definición no disponible."),
                "categoria": categoria
            },
            "position": {"x": pos_x, "y": pos_y},
        }

        relaciones.append({"id": f"e0-{id_counter}", "source": "0", "target": str(id_counter)})

        id_counter += 1

    # Extraer verbos como procesos adicionales y conectarlos según proximidad
    for sent in doc.sents:
        sent_doc = nlp(sent.text)
        # Términos en esta oración
        terminos_en_sent = [span.text.lower() for match_id, start, end in matcher(sent_doc) for span in [sent_doc[start:end]]]
        verbos = [token.lemma_ for token in sent_doc if token.pos_ == "VERB"]

        for termino in terminos_en_sent:
            term_id = next((k for k, v in nodos.items() if v["data"]["label"].lower() == termino), None)
            if term_id:
                for verbo in verbos:
                    verbo_lower = verbo.lower()
                    # Solo agregar verbo si no es repetido y relevante
                    if verbo_lower in terminos_petro:
                        nodo_verbo_id = None
                        for k, v in nodos.items():
                            if v["data"]["label"].lower() == verbo_lower:
                                nodo_verbo_id = k
                                break
                        if not nodo_verbo_id:
                            nodo_verbo_id = str(id_counter)
                            nodos[nodo_verbo_id] = {
                                "id": nodo_verbo_id,
                                "data": {
                                    "label": verbo.capitalize(),
                                    "description": "Proceso relacionado.",
                                    "categoria": "proceso"
                                },
                                "position": {
                                    "x": nodos[term_id]["position"]["x"] + 150,
                                    "y": nodos[term_id]["position"]["y"] + 20
                                }
                            }
                            id_counter += 1
                        relaciones.append({"id": f"e{term_id}-{nodo_verbo_id}", "source": term_id, "target": nodo_verbo_id})

    elementos = list(nodos.values()) + relaciones
    return {"elements": elementos}

npm install react-tooltip

// Archivo: NodoConTooltip.js
import React from 'react';
import ReactTooltip from 'react-tooltip';

export default function NodoConTooltip({ id, data }) {
  return (
    <>
      <div data-tip data-for={`tooltip-${id}`} style={{ padding: 5, cursor: 'pointer' }}>
        {data.label}
      </div>
      <ReactTooltip id={`tooltip-${id}`} place="top" effect="solid" multiline={true} >
        <span>{data.description || "Sin definición disponible."}</span>
      </ReactTooltip>
    </>
  );
}

import React from 'react';
import ReactFlow, { MiniMap, Controls, Background } from 'react-flow-renderer';
import NodoConTooltip from './NodoConTooltip';

const nodeTypes = {
  customNode: NodoConTooltip,
};

const MapaMental = ({ elements }) => {
  if (!elements) return <p>Cargando mapa mental...</p>;

  return (
    <div style={{ height: 600, border: '1px solid #ddd', marginTop: 20 }}>
      <h3>Mapa Mental Conceptual Dinámico</h3>
      <ReactFlow
        elements={elements}
        nodeTypes={nodeTypes}
        snapToGrid={true}
        snapGrid={[15, 15]}
      >
        <MiniMap />
        <Controls />
        <Background color="#aaa" gap={16} />
      </ReactFlow>
    </div>
  );
};

export default MapaMental;